### ISSUE TITLE
OutOfBoundsException when compiling FungibleToken Example

### ISSUE THREAD

**Issue by ykoitzsch** [neow3j/neow3j-examples-java#13]
Compiling/deploying the FungibleToken example smart contract with CompileAndDeploy.java, throws the following exception:

`Exception in thread "main" java.lang.IndexOutOfBoundsException
        at org.objectweb.asm.tree.InsnList.get(InsnList.java:94)
        at io.neow3j.compiler.NeoMethod.convert(NeoMethod.java:486)
        at io.neow3j.compiler.converters.MethodsConverter.handleUncachedMethodCall(MethodsConverter.java:193)
        at io.neow3j.compiler.converters.MethodsConverter.handleMethodCall(MethodsConverter.java:167)
        at io.neow3j.compiler.converters.MethodsConverter.handleInvoke(MethodsConverter.java:148)
        at io.neow3j.compiler.converters.MethodsConverter.convert(MethodsConverter.java:81)
        at io.neow3j.compiler.Compiler.handleInsn(Compiler.java:404)
        at io.neow3j.compiler.converters.ObjectsConverter.handleStringConcatenation(ObjectsConverter.java:301)
        at io.neow3j.compiler.converters.ObjectsConverter.handleNew(ObjectsConverter.java:167)
        at io.neow3j.compiler.converters.ObjectsConverter.convert(ObjectsConverter.java:83)
        at io.neow3j.compiler.Compiler.handleInsn(Compiler.java:404)
        at io.neow3j.compiler.NeoMethod.convert(NeoMethod.java:488)
        at io.neow3j.compiler.converters.MethodsConverter.handleUncachedMethodCall(MethodsConverter.java:193)
        at io.neow3j.compiler.converters.MethodsConverter.handleMethodCall(MethodsConverter.java:167)
        at io.neow3j.compiler.converters.MethodsConverter.handleInvoke(MethodsConverter.java:148)
        at io.neow3j.compiler.converters.MethodsConverter.convert(MethodsConverter.java:81)
        at io.neow3j.compiler.Compiler.handleInsn(Compiler.java:404)
        at io.neow3j.compiler.NeoMethod.convert(NeoMethod.java:488)
        at io.neow3j.compiler.Compiler.compile(Compiler.java:271)
        at io.neow3j.compiler.Compiler.compile(Compiler.java:240)
        at io.neow3j.examples.contractdevelopment.CompileAndDeploy.main(CompileAndDeploy.java:26)`

**Comment by gsmachado** [comment]
Thanks for the report, @ykoitzsch! Indeed, strange... 🤔 

We'll check that and get back to you as soon as possible. 👍

**Comment by mialbu** [comment]
Hey @ykoitzsch thanks for the issue. I looked into it quickly and already found an invalid call to the `toString()` method. (line 101)
I changed it to `toByteArray()`, which is the correct way in that case. I could compile and deploy it successfully now.
